import { connectToDatabase } from "./mongodb";
import { CompanyModel } from "./models/Company";

export const mockCompanies = [
  {
    name: "Verdn",
    domain: "verdn.com",
    website: "https://verdn.com",
    stage: "Seed",
    sector: "Climate Tech",
    tags: ["sustainability", "b2b", "saas", "api"],
    location: "London, UK",
    founded: 2021,
    employees: "11-50",
    description: "Verdn lets companies embed sustainability pledges directly into their products and checkout flows via API.",
    signals: [
      { id: "s1", type: "hiring", title: "Hiring Backend Engineer", description: "Posted 2 senior backend roles on LinkedIn", date: "2024-01-15", source: "linkedin.com" },
      { id: "s2", type: "product", title: "New API v2 launched", description: "Released major API version with webhook support", date: "2024-01-02", source: "verdn.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Campfire",
    domain: "campfire.to",
    website: "https://campfire.to",
    stage: "Pre-Seed",
    sector: "Developer Tools",
    tags: ["developer-tools", "collaboration", "realtime", "b2b"],
    location: "San Francisco, CA",
    founded: 2023,
    employees: "1-10",
    description: "Campfire is a real-time collaboration SDK that lets developers embed multiplayer features into any app in minutes.",
    signals: [
      { id: "s1", type: "product", title: "Public beta launched", description: "Opened beta to 500+ waitlist developers", date: "2024-01-10", source: "campfire.to" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Fern",
    domain: "buildwithfern.com",
    website: "https://buildwithfern.com",
    stage: "Seed",
    sector: "Developer Tools",
    tags: ["developer-tools", "api", "documentation", "sdk-generation"],
    location: "New York, NY",
    founded: 2022,
    employees: "11-50",
    description: "Fern generates beautiful API documentation and type-safe SDKs from an OpenAPI spec, used by teams like Scale AI and Cohere.",
    signals: [
      { id: "s1", type: "funding", title: "Raised $4M Seed", description: "Closed seed round led by Spark Capital", date: "2023-11-01", source: "techcrunch.com" },
      { id: "s2", type: "hiring", title: "Expanding team", description: "3 open roles including Head of Growth", date: "2024-01-20", source: "linkedin.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Basehub",
    domain: "basehub.com",
    website: "https://basehub.com",
    stage: "Pre-Seed",
    sector: "Developer Tools",
    tags: ["cms", "developer-tools", "headless", "ai"],
    location: "Buenos Aires, Argentina",
    founded: 2023,
    employees: "1-10",
    description: "Basehub is an AI-native headless CMS built for developers, with a type-safe query API and native AI blocks.",
    signals: [
      { id: "s1", type: "product", title: "AI Blocks feature launch", description: "Launched AI-powered content blocks enabling dynamic generation", date: "2024-01-08", source: "basehub.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Composio",
    domain: "composio.dev",
    website: "https://composio.dev",
    stage: "Seed",
    sector: "AI Infrastructure",
    tags: ["ai", "agents", "integrations", "developer-tools", "b2b"],
    location: "San Francisco, CA",
    founded: 2023,
    employees: "11-50",
    description: "Composio provides 200+ pre-built integrations for AI agents, letting LLM apps connect to Gmail, Slack, GitHub, and more with a single API.",
    signals: [
      { id: "s1", type: "product", title: "200 integrations milestone", description: "Hit 200 live integrations across SaaS tools", date: "2024-01-12", source: "composio.dev" },
      { id: "s2", type: "hiring", title: "Hiring AI engineers", description: "3 roles for AI/ML engineers with agent experience", date: "2024-01-18", source: "linkedin.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Browserbase",
    domain: "browserbase.com",
    website: "https://browserbase.com",
    stage: "Seed",
    sector: "AI Infrastructure",
    tags: ["browser-automation", "ai", "scraping", "agents", "developer-tools"],
    location: "San Francisco, CA",
    founded: 2023,
    employees: "11-50",
    description: "Browserbase is a headless browser infrastructure platform purpose-built for AI agents to reliably navigate and interact with the web.",
    signals: [
      { id: "s1", type: "funding", title: "Raised $6M Seed", description: "Seed round to scale browser cloud infrastructure", date: "2023-12-15", source: "techcrunch.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Inngest",
    domain: "inngest.com",
    website: "https://inngest.com",
    stage: "Series A",
    sector: "Developer Tools",
    tags: ["developer-tools", "background-jobs", "serverless", "workflow", "b2b"],
    location: "Remote",
    founded: 2021,
    employees: "11-50",
    description: "Inngest is a durable workflow and background job platform for serverless environments, with zero infrastructure to manage.",
    signals: [
      { id: "s1", type: "funding", title: "Raised $13M Series A", description: "Series A led by a16z to expand workflow platform", date: "2023-10-01", source: "a16z.com" },
      { id: "s2", type: "product", title: "AI function support", description: "Native support for long-running AI inference tasks", date: "2024-01-05", source: "inngest.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Trigger.dev",
    domain: "trigger.dev",
    website: "https://trigger.dev",
    stage: "Seed",
    sector: "Developer Tools",
    tags: ["developer-tools", "background-jobs", "open-source", "typescript"],
    location: "Dublin, Ireland",
    founded: 2022,
    employees: "11-50",
    description: "Trigger.dev is an open-source background jobs framework for TypeScript developers that feels native to their existing codebase.",
    signals: [
      { id: "s1", type: "product", title: "v3 launch with Realtime", description: "Major release adding real-time progress streaming for long jobs", date: "2024-01-14", source: "trigger.dev" },
      { id: "s2", type: "hiring", title: "Hiring DX engineer", description: "Seeking developer experience engineer for OSS community", date: "2024-01-20", source: "linkedin.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Mintlify",
    domain: "mintlify.com",
    website: "https://mintlify.com",
    stage: "Series A",
    sector: "Developer Tools",
    tags: ["documentation", "developer-tools", "ai", "b2b", "saas"],
    location: "San Francisco, CA",
    founded: 2021,
    employees: "11-50",
    description: "Mintlify is the documentation platform for high-growth API companies, with AI-powered search, auto-generated changelogs, and beautiful out-of-the-box UI.",
    signals: [
      { id: "s1", type: "funding", title: "Raised $18M Series A", description: "Series A round to expand AI documentation features", date: "2023-09-15", source: "techcrunch.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Resend",
    domain: "resend.com",
    website: "https://resend.com",
    stage: "Series A",
    sector: "Developer Tools",
    tags: ["email", "developer-tools", "api", "transactional", "b2b"],
    location: "San Francisco, CA",
    founded: 2022,
    employees: "11-50",
    description: "Resend is the email API for developers, offering React-based email templating, deliverability analytics, and a best-in-class DX.",
    signals: [
      { id: "s1", type: "funding", title: "Raised $8M Series A", description: "Funding to scale developer email infrastructure", date: "2023-08-01", source: "techcrunch.com" },
      { id: "s2", type: "product", title: "React Email 2.0", description: "Launched major version of open-source React Email library", date: "2024-01-03", source: "resend.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Neon",
    domain: "neon.tech",
    website: "https://neon.tech",
    stage: "Series B",
    sector: "Data Infrastructure",
    tags: ["database", "postgres", "serverless", "developer-tools", "infrastructure"],
    location: "Remote",
    founded: 2021,
    employees: "51-200",
    description: "Neon is serverless Postgres with instant branching, autoscaling to zero, and a generous free tier — built for modern cloud-native applications.",
    signals: [
      { id: "s1", type: "funding", title: "Raised $46M Series B", description: "Series B to scale serverless Postgres infrastructure globally", date: "2023-08-10", source: "techcrunch.com" },
      { id: "s2", type: "product", title: "Vercel partnership deepened", description: "First-class integration with Vercel Postgres now powered by Neon", date: "2023-11-15", source: "neon.tech" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Turso",
    domain: "turso.tech",
    website: "https://turso.tech",
    stage: "Seed",
    sector: "Data Infrastructure",
    tags: ["database", "sqlite", "edge", "developer-tools", "embedded"],
    location: "Remote",
    founded: 2022,
    employees: "11-50",
    description: "Turso is an edge-native SQLite database built on libSQL, enabling sub-millisecond queries globally with per-tenant database isolation.",
    signals: [
      { id: "s1", type: "product", title: "Embedded replicas GA", description: "Launched embedded replicas for offline-first and local-first apps", date: "2024-01-10", source: "turso.tech" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Warp",
    domain: "warp.dev",
    website: "https://warp.dev",
    stage: "Series B",
    sector: "Developer Tools",
    tags: ["terminal", "developer-tools", "ai", "productivity", "b2c"],
    location: "San Francisco, CA",
    founded: 2020,
    employees: "51-200",
    description: "Warp is an AI-powered terminal built in Rust, with built-in command search, intelligent autocomplete, and collaborative notebooks.",
    signals: [
      { id: "s1", type: "funding", title: "Raised $23M Series B", description: "Series B to expand Warp for Teams enterprise offering", date: "2023-05-01", source: "techcrunch.com" },
      { id: "s2", type: "product", title: "Warp AI launch", description: "Launched conversational AI within the terminal for command generation", date: "2023-09-20", source: "warp.dev" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Railway",
    domain: "railway.app",
    website: "https://railway.app",
    stage: "Series A",
    sector: "Cloud Infrastructure",
    tags: ["deployment", "infrastructure", "developer-tools", "paas", "b2b"],
    location: "San Francisco, CA",
    founded: 2020,
    employees: "11-50",
    description: "Railway is a deployment platform that eliminates DevOps complexity — provision infrastructure, deploy apps, and scale all from a single pane of glass.",
    signals: [
      { id: "s1", type: "product", title: "Regions GA", description: "Launched multi-region deployments across US, EU, and APAC", date: "2024-01-08", source: "railway.app" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Depot",
    domain: "depot.dev",
    website: "https://depot.dev",
    stage: "Seed",
    sector: "Developer Tools",
    tags: ["ci-cd", "docker", "build", "developer-tools", "devops"],
    location: "Remote",
    founded: 2022,
    employees: "1-10",
    description: "Depot accelerates Docker image builds by 40x using remote build infrastructure with intelligent caching and native ARM support.",
    signals: [
      { id: "s1", type: "product", title: "GitHub Actions native integration", description: "Released drop-in GitHub Actions replacement for Docker builds", date: "2024-01-05", source: "depot.dev" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Unkey",
    domain: "unkey.dev",
    website: "https://unkey.dev",
    stage: "Pre-Seed",
    sector: "Developer Tools",
    tags: ["api-keys", "auth", "developer-tools", "open-source", "security"],
    location: "Remote",
    founded: 2023,
    employees: "1-10",
    description: "Unkey is an open-source API key management platform with built-in rate limiting, analytics, and per-key permissions — deployable in minutes.",
    signals: [
      { id: "s1", type: "product", title: "Semantic caching feature", description: "Launched semantic caching for LLM API responses reducing costs", date: "2024-01-16", source: "unkey.dev" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Clerk",
    domain: "clerk.com",
    website: "https://clerk.com",
    stage: "Series B",
    sector: "Developer Tools",
    tags: ["auth", "identity", "developer-tools", "b2b", "saas"],
    location: "San Francisco, CA",
    founded: 2021,
    employees: "51-200",
    description: "Clerk is the most complete authentication and user management platform for modern web apps — with prebuilt components, B2B orgs, and MFA.",
    signals: [
      { id: "s1", type: "funding", title: "Raised $30M Series B", description: "Series B led by Madrona to scale auth platform", date: "2023-06-15", source: "techcrunch.com" },
      { id: "s2", type: "product", title: "B2B orgs GA", description: "Launched complete B2B multi-tenancy with org switching and RBAC", date: "2024-01-12", source: "clerk.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Permit.io",
    domain: "permit.io",
    website: "https://permit.io",
    stage: "Series A",
    sector: "Developer Tools",
    tags: ["authorization", "rbac", "abac", "developer-tools", "b2b", "security"],
    location: "Tel Aviv, Israel",
    founded: 2021,
    employees: "11-50",
    description: "Permit.io is a full-stack authorization platform that lets developers add fine-grained RBAC/ABAC permissions to any application without rebuilding auth logic.",
    signals: [
      { id: "s1", type: "funding", title: "Raised $8M Series A", description: "Series A to expand enterprise authorization platform", date: "2023-07-01", source: "techcrunch.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "WorkOS",
    domain: "workos.com",
    website: "https://workos.com",
    stage: "Series B",
    sector: "Developer Tools",
    tags: ["enterprise-auth", "sso", "scim", "b2b", "saas", "developer-tools"],
    location: "San Francisco, CA",
    founded: 2019,
    employees: "51-200",
    description: "WorkOS is the developer platform for enterprise features — SSO, SCIM, Fine-Grained Authorization, and Admin Portal — enabling startups to land enterprise deals.",
    signals: [
      { id: "s1", type: "product", title: "AuthKit launch", description: "Free authentication kit competitive with Auth0 for startup-scale apps", date: "2023-10-05", source: "workos.com" },
    ],
    notes: [],
    savedToLists: [],
  },
  {
    name: "Stytch",
    domain: "stytch.com",
    website: "https://stytch.com",
    stage: "Series B",
    sector: "Developer Tools",
    tags: ["auth", "b2b", "passkeys", "fraud-prevention", "developer-tools"],
    location: "San Francisco, CA",
    founded: 2020,
    employees: "51-200",
    description: "Stytch provides flexible authentication APIs for both consumer and B2B apps, with passkeys, fraud signals, and headless SDKs for full customization.",
    signals: [
      { id: "s1", type: "product", title: "B2B SaaS auth suite", description: "Launched dedicated B2B auth suite with orgs, SSO, and RBAC", date: "2023-12-01", source: "stytch.com" },
    ],
    notes: [],
    savedToLists: [],
  },
];

export async function seedDatabase() {
  await connectToDatabase();
  const count = await CompanyModel.countDocuments();
  if (count > 0) {
    console.log(`Database already has ${count} companies. Skipping seed.`);
    return;
  }
  await CompanyModel.insertMany(mockCompanies);
  console.log(`Seeded ${mockCompanies.length} companies.`);
}